branches:
  only:
    - master
    - develop
language: node_js
node_js:
  - stable
  - 4
  - 5
  - 6
script:
  - npm run build
before_script:
  - npm install -g gulp webpack
  - npm install -g node-dev
